#
# Author: Raul Perusquia <raul@inikoo.com>
# Created: Fri, 3:36 om 15/3/2024 Malaysia Time, Kuala Lumpur, Malaysia
# Copyright (c) 2023, Raul A Perusquia Flores
#

echo "dumping sql from au origin 🍬"
rm *.sql
mysqldump --no-tablespaces dw    'Inventory Transaction Fact' 'Order Transaction Fact' 'Order No Product Transaction Fact' 'Product Dimension' 'Product History Dimension' 'Product Part Bridge' 'Invoice Dimension' 'Order Dimension' 'Delivery Note Dimension' 'Webpage Type Dimension' 'Customer Client Dimension' 'Attachment Bridge' 'Page Store Dimension' 'Shipping Zone Schema Dimension' 'Shipping Zone Dimension' 'Charge Dimension' 'Customer Fulfilment Dimension' 'Fulfilment Delivery Dimension' 'Fulfilment Rent Transaction Fact' 'Fulfilment Transaction Fact' 'Fulfilment Asset Dimension' 'Customer Dimension' 'Customer Deleted Dimension' 'Prospect Dimension' 'Website User Dimension' 'User Group User Bridge' 'Picking Pipeline Dimension' 'Location Picking Pipeline Bridge' 'Product Category Dimension' 'Shipper Dimension' 'Purchase Order Deleted Dimension' 'Purchase Order Transaction Fact' 'Part Location Dimension'  'Part Category Dimension' 'Category Dimension' 'Category Bridge' 'Part Deleted Dimension' 'Supplier Deleted Dimension' 'Supplier Part Deleted Dimension' 'Warehouse Dimension' 'Warehouse Area Dimension' 'Location Dimension' 'Location Deleted Dimension' 'Agent Supplier Bridge' 'Supplier Dimension' 'Payment Account Store Bridge'  'Payment Dimension' 'Payment Account Dimension' 'Payment Service Provider Dimension'  'Website Dimension' 'Email Campaign Type Dimension' 'Store Dimension'  'Staff Deleted Dimension' 'Image Dimension'  'Image Subject Bridge' 'Staff Role Bridge' 'Account Dimension' 'Account Data' 'Staff Dimension' 'User Dimension' 'Agent Dimension' 'Supplier Data' 'Supplier Part Dimension' 'Purchase Order Dimension' 'Supplier Delivery Dimension' 'Part Dimension' 'pika_fetch' 'pika_fetch_error' > dw_base.sql &
mysqldump --no-tablespaces sk    'Inventory Transaction Fact' 'Order Transaction Fact' 'Order No Product Transaction Fact' 'Product Dimension' 'Product History Dimension' 'Product Part Bridge' 'Invoice Dimension' 'Order Dimension' 'Delivery Note Dimension' 'Webpage Type Dimension' 'Customer Client Dimension' 'Attachment Bridge' 'Page Store Dimension' 'Shipping Zone Schema Dimension' 'Shipping Zone Dimension' 'Charge Dimension' 'Customer Fulfilment Dimension' 'Fulfilment Delivery Dimension' 'Fulfilment Rent Transaction Fact' 'Fulfilment Transaction Fact' 'Fulfilment Asset Dimension' 'Customer Dimension' 'Customer Deleted Dimension' 'Prospect Dimension' 'Website User Dimension' 'User Group User Bridge' 'Picking Pipeline Dimension' 'Location Picking Pipeline Bridge' 'Product Category Dimension' 'Shipper Dimension' 'Purchase Order Deleted Dimension' 'Purchase Order Transaction Fact' 'Part Location Dimension'  'Part Category Dimension' 'Category Dimension' 'Category Bridge' 'Part Deleted Dimension' 'Supplier Deleted Dimension' 'Supplier Part Deleted Dimension' 'Warehouse Dimension' 'Warehouse Area Dimension' 'Location Dimension' 'Location Deleted Dimension' 'Agent Supplier Bridge' 'Supplier Dimension' 'Payment Account Store Bridge'  'Payment Dimension' 'Payment Account Dimension' 'Payment Service Provider Dimension'  'Website Dimension' 'Email Campaign Type Dimension' 'Store Dimension'  'Staff Deleted Dimension' 'Image Dimension'  'Image Subject Bridge' 'Staff Role Bridge' 'Account Dimension' 'Account Data' 'Staff Dimension' 'User Dimension' 'Agent Dimension' 'Supplier Data' 'Supplier Part Dimension' 'Purchase Order Dimension' 'Supplier Delivery Dimension' 'Part Dimension' 'pika_fetch' 'pika_fetch_error' > sk_base.sql &
mysqldump --no-tablespaces es    'Inventory Transaction Fact' 'Order Transaction Fact' 'Order No Product Transaction Fact' 'Product Dimension' 'Product History Dimension' 'Product Part Bridge' 'Invoice Dimension' 'Order Dimension' 'Delivery Note Dimension' 'Webpage Type Dimension' 'Customer Client Dimension' 'Attachment Bridge' 'Page Store Dimension' 'Shipping Zone Schema Dimension' 'Shipping Zone Dimension' 'Charge Dimension' 'Customer Fulfilment Dimension' 'Fulfilment Delivery Dimension' 'Fulfilment Rent Transaction Fact' 'Fulfilment Transaction Fact' 'Fulfilment Asset Dimension' 'Customer Dimension' 'Customer Deleted Dimension' 'Prospect Dimension' 'Website User Dimension' 'User Group User Bridge' 'Picking Pipeline Dimension' 'Location Picking Pipeline Bridge' 'Product Category Dimension' 'Shipper Dimension' 'Purchase Order Deleted Dimension' 'Purchase Order Transaction Fact' 'Part Location Dimension'  'Part Category Dimension' 'Category Dimension' 'Category Bridge' 'Part Deleted Dimension' 'Supplier Deleted Dimension' 'Supplier Part Deleted Dimension' 'Warehouse Dimension' 'Warehouse Area Dimension' 'Location Dimension' 'Location Deleted Dimension' 'Agent Supplier Bridge' 'Supplier Dimension' 'Payment Account Store Bridge'  'Payment Dimension' 'Payment Account Dimension' 'Payment Service Provider Dimension'  'Website Dimension' 'Email Campaign Type Dimension' 'Store Dimension'  'Staff Deleted Dimension' 'Image Dimension'  'Image Subject Bridge' 'Staff Role Bridge' 'Account Dimension' 'Account Data' 'Staff Dimension' 'User Dimension' 'Agent Dimension' 'Supplier Data' 'Supplier Part Dimension' 'Purchase Order Dimension' 'Supplier Delivery Dimension' 'Part Dimension' 'pika_fetch' 'pika_fetch_error' > es_base.sql &
mysqldump --no-tablespaces aroma 'Inventory Transaction Fact' 'Order Transaction Fact' 'Order No Product Transaction Fact' 'Product Dimension' 'Product History Dimension' 'Product Part Bridge' 'Invoice Dimension' 'Order Dimension' 'Delivery Note Dimension' 'Webpage Type Dimension' 'Customer Client Dimension' 'Attachment Bridge' 'Page Store Dimension' 'Shipping Zone Schema Dimension' 'Shipping Zone Dimension' 'Charge Dimension' 'Customer Fulfilment Dimension' 'Fulfilment Delivery Dimension' 'Fulfilment Rent Transaction Fact' 'Fulfilment Transaction Fact' 'Fulfilment Asset Dimension' 'Customer Dimension' 'Customer Deleted Dimension' 'Prospect Dimension' 'Website User Dimension' 'User Group User Bridge' 'Picking Pipeline Dimension' 'Location Picking Pipeline Bridge' 'Product Category Dimension' 'Shipper Dimension' 'Purchase Order Deleted Dimension' 'Purchase Order Transaction Fact' 'Part Location Dimension'  'Part Category Dimension' 'Category Dimension' 'Category Bridge' 'Part Deleted Dimension' 'Supplier Deleted Dimension' 'Supplier Part Deleted Dimension' 'Warehouse Dimension' 'Warehouse Area Dimension' 'Location Dimension' 'Location Deleted Dimension' 'Agent Supplier Bridge' 'Supplier Dimension' 'Payment Account Store Bridge'  'Payment Dimension' 'Payment Account Dimension' 'Payment Service Provider Dimension'  'Website Dimension' 'Email Campaign Type Dimension' 'Store Dimension'  'Staff Deleted Dimension' 'Image Dimension'  'Image Subject Bridge' 'Staff Role Bridge' 'Account Dimension' 'Account Data' 'Staff Dimension' 'User Dimension' 'Agent Dimension' 'Supplier Data' 'Supplier Part Dimension' 'Purchase Order Dimension' 'Supplier Delivery Dimension' 'Part Dimension' 'pika_fetch' 'pika_fetch_error' > aroma_base.sql &
mysqldump --no-tablespaces indo  'Inventory Transaction Fact' 'Order Transaction Fact' 'Order No Product Transaction Fact' 'Product Dimension' 'Product History Dimension' 'Product Part Bridge' 'Invoice Dimension' 'Order Dimension' 'Delivery Note Dimension' 'Webpage Type Dimension' 'Customer Client Dimension' 'Attachment Bridge' 'Page Store Dimension' 'Shipping Zone Schema Dimension' 'Shipping Zone Dimension' 'Charge Dimension' 'Customer Fulfilment Dimension' 'Fulfilment Delivery Dimension' 'Fulfilment Rent Transaction Fact' 'Fulfilment Transaction Fact' 'Fulfilment Asset Dimension' 'Customer Dimension' 'Customer Deleted Dimension' 'Prospect Dimension' 'Website User Dimension' 'User Group User Bridge' 'Picking Pipeline Dimension' 'Location Picking Pipeline Bridge' 'Product Category Dimension' 'Shipper Dimension' 'Purchase Order Deleted Dimension' 'Purchase Order Transaction Fact' 'Part Location Dimension'  'Part Category Dimension' 'Category Dimension' 'Category Bridge' 'Part Deleted Dimension' 'Supplier Deleted Dimension' 'Supplier Part Deleted Dimension' 'Warehouse Dimension' 'Warehouse Area Dimension' 'Location Dimension' 'Location Deleted Dimension' 'Agent Supplier Bridge' 'Supplier Dimension' 'Payment Account Store Bridge'  'Payment Dimension' 'Payment Account Dimension' 'Payment Service Provider Dimension'  'Website Dimension' 'Email Campaign Type Dimension' 'Store Dimension'  'Staff Deleted Dimension' 'Image Dimension'  'Image Subject Bridge' 'Staff Role Bridge' 'Account Dimension' 'Account Data' 'Staff Dimension' 'User Dimension' 'Agent Dimension' 'Supplier Data' 'Supplier Part Dimension' 'Purchase Order Dimension' 'Supplier Delivery Dimension' 'Part Dimension' 'pika_fetch' 'pika_fetch_error' > indo_base.sql &

wait;
echo "loading to db"
mysql indo_base <  indo_base.sql;
echo "indo done 🎉"
mysql aroma_base <  aroma_base.sql;
echo "aroma done 🎉"
mysql es_base <  es_base.sql;
echo "es done 🎉"
mysql sk_base <  sk_base.sql;
echo "sk done 🎉"
mysql dw_base <  dw_base.sql;
echo "dw done 🎉"

