php artisan tenants:artisan "ide-helper:models  -Wr  --ignore='App\Models\Central\Group,App\Models\Helpers\CurrencyExchange,App\Models\Assets\TariffCode,App\Models\Assets\Country,App\Models\Assets\Currency,App\Models\Assets\Language,App\Models\Assets\Timezone,App\Models\Central\CentralUser,App\Models\Tenancy\Tenant,App\Models\Tenancy\TenantInventoryStats,App\Models\Tenancy\TenantStats,App\Models\Central\CentralUserTenant,App\Models\Central\User,App\Models\Central\Admin,App\Models\Central\AdminUser,App\Models\Central\Deployment,App\Models\Tenancy\TenantMarketingStats,App\Models\Tenancy\TenantProcurementStats,App\Models\Tenancy\TenantAccountingStats'" --tenant=aroma
php artisan ide-helper:models -Wr 'App\Models\Assets\Country'
php artisan ide-helper:models -Wr 'App\Models\Assets\Currency'
php artisan ide-helper:models -Wr 'App\Models\Assets\Language'
php artisan ide-helper:models -Wr 'App\Models\Assets\Timezone'
php artisan ide-helper:models -Wr 'App\Models\Central\CentralUser'
php artisan ide-helper:models -Wr 'App\Models\Central\CentralDomain'
php artisan ide-helper:models -Wr 'App\Models\Tenancy\Tenant'
php artisan ide-helper:models -Wr 'App\Models\Tenancy\TenantInventoryStats'
php artisan ide-helper:models -Wr 'App\Models\Tenancy\TenantStats'
php artisan ide-helper:models -Wr 'App\Models\Central\CentralUserTenant'
php artisan ide-helper:models -Wr 'App\Models\Central\User'
php artisan ide-helper:models -Wr 'App\Models\SysAdmin\Admin'
php artisan ide-helper:models -Wr 'App\Models\SysAdmin\AdminUser'
php artisan ide-helper:models -Wr 'App\Models\DevOps\Deployment'
php artisan ide-helper:models -Wr 'App\Models\Tenancy\TenantMarketingStats'
php artisan ide-helper:models -Wr 'App\Models\Tenancy\TenantProcurementStats'
php artisan ide-helper:models -Wr 'App\Models\Tenancy\TenantAccountingStats'
php artisan ide-helper:models -Wr 'App\Models\Assets\TariffCode'
php artisan ide-helper:models -Wr 'App\Models\Helpers\CurrencyExchange'
php artisan ide-helper:models -Wr 'App\Models\Tenancy\Group'


